feat: add entitys

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -18,13 +18,13 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-# 3. Запуск тестов
-#echo "🧪 Running tests..."
-#./mvnw test
-#if [ $? -ne 0 ]; then
-#    echo "❌ Tests failed"
-#    exit 1
-#fi
+ 3. Запуск тестов
+echo "🧪 Running tests..."
+./mvnw test
+if [ $? -ne 0 ]; then
+    echo "❌ Tests failed"
+    exit 1
+fi
 
 # 4. Сборка проекта
 #echo "🔨 Building project..."
